### ISSUE TITLE
Fork direction is misleading

### ISSUE THREAD

**Issue by nponeccop** [p-alik/gearmand#9]
I don't know how to fix it. Maybe deleting this repo and forking from gearman/gearmand will do.

**Comment by p-alik** [comment]
This repo is ahead of [gearman/gearmand]. See [#134](https://github.com/gearman/gearmand/issues/134#issuecomment-319882188)

**Comment by nponeccop** [comment]
It's still not a  common practice. The "main" repo is `gearman/gearmand`, so a common approach is to use branches there if you want separate development branch.

It's up to you though. IMO you should at least document this uncommon structure of repos and using forks instead of branches in Readme.md of `gearman/gearmand`.

**Comment by p-alik** [comment]
I'm deeply disappointed  to mislead you, but I had a particular reason to take ahead of origin repo.

>  IMO you should at least document this uncommon structure of repos and using forks instead of branches in Readme.md of gearman/gearmand.

It's mentioned in repo description: This repository may be slightly ahead of the https://github.com/gearman/gearmand

**Comment by nponeccop** [comment]
Being ahead or behind is unrelated to forking direction. I don't understand why you put being ahead as an argument. Anyway, it's a minor issue.
